version: "3.9"
services:
    db:
        build: db/
        ports: 
            - 3306:3306
        networks: 
            queezienet:
                ipv4_address: 172.20.0.2
    api:
        build: queezieApi/
        ports: 
            - 3000:3000
        networks: 
            queezienet:
                ipv4_address: 172.20.0.3
    front:
        build: FrontEnd/
        ports:
            - 80:80
        networks: 
            queezienet:
                ipv4_address: 172.20.0.4

networks:
    queezienet:
        driver: bridge
        enable_ipv6: false
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16
                  gateway: 172.20.0.1
